import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarWrapper from "@/components/SidebarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GenPass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarWrapper>
        {children}
        </SidebarWrapper>
      </body>
    </html>
  );
}


// import { ThemeProvider as NextThemesProvider } from "next-themes";
// import React, { useState } from "react";
// import { Sidebar, SidebarBody, SidebarLink } from "@/components/ui/sidebar";
// import {
//   IconArrowLeft,
//   IconBrandTabler,
//   IconSettings,
//   IconUserBolt,
// } from "@tabler/icons-react";
// import Link from "next/link";
// import { motion } from "motion/react";
// import Image from "next/image";
// import { cn } from "@/lib/utils";

// export default function RootLayout({
//     children,
//   }: Readonly<{
//     children: React.ReactNode;
//   }>) {
//   const links = [
//     {
//       label: "Password Analysis",
//       href: "/",
//       icon: (
//         <IconBrandTabler className="h-5 w-5 shrink-0 text-neutral-700 dark:text-neutral-200" />
//       ),
//     },
//     {
//       label: "Generate Password",
//       href: "/generate",
//       icon: (
//         <IconUserBolt className="h-5 w-5 shrink-0 text-neutral-700 dark:text-neutral-200" />
//       ),
//     },
//     {
//       label: "Tips",
//       href: "/tips",
//       icon: (
//         <IconSettings className="h-5 w-5 shrink-0 text-neutral-700 dark:text-neutral-200" />
//       ),
//     },
//     // {
//     //   label: "Logout",
//     //   href: "#",
//     //   icon: (
//     //     <IconArrowLeft className="h-5 w-5 shrink-0 text-neutral-700 dark:text-neutral-200" />
//     //   ),
//     // },
//   ];
//   const [open, setOpen] = useState(true);
//   return (
//     <html>
//        <body>
//        <NextThemesProvider
//           attribute="class"
//           defaultTheme="system"
//           value={{
//             light: "light",
//             dark: "dark",
//           }}
//         >             
//     <div
//       className={cn(
//         "mx-auto flex w-full flex-1 flex-col overflow-hidden rounded-md border border-neutral-200 bg-gray-100 md:flex-row dark:border-neutral-700 dark:bg-neutral-800",
//         "h-[100vh]", // for your use case, use `h-screen` instead of `h-[60vh]`
//       )}
//     >
//       <Sidebar open={open} setOpen={setOpen}>
//         <SidebarBody className="justify-between gap-10 ">
//           <div className="flex flex-1 flex-col overflow-x-hidden overflow-y-auto ">
//             {open ? <Logo /> : <LogoIcon />}
//             <div className="mt-8 flex flex-col gap-2 ">
//               {links.map((link, idx) => (
//                 <SidebarLink key={idx} link={link} />
//               ))}
//             </div>
//           </div>
//           <div>
//             <SidebarLink
//               link={{
//                 label: "Achintya Gulati",
//                 href: "#",
//                 icon: (
//                   <Image
//                     src="https://assets.aceternity.com/manu.png"
//                     className="h-7 w-7 shrink-0 rounded-full"
//                     width={50}
//                     height={50}
//                     alt="Avatar"
//                   />
//                 ),
//               }}
//             />
//           </div>
//         </SidebarBody>
//       </Sidebar>
//       {/* <Dashboard/> */}
//       <div className="relative flex h-[100vh] w-full items-center justify-center bg-white dark:bg-black">
//       <div
//         className={cn(
//           "absolute inset-0",
//           "[background-size:40px_40px]",
//           "[background-image:linear-gradient(to_right,#e4e4e7_1px,transparent_1px),linear-gradient(to_bottom,#e4e4e7_1px,transparent_1px)]",
//           "dark:[background-image:linear-gradient(to_right,#262626_1px,transparent_1px),linear-gradient(to_bottom,#262626_1px,transparent_1px)]",
//         )}
//       />
//       {/* Radial gradient for the container to give a faded look */}
//       <div className="pointer-events-none absolute inset-0 flex items-center justify-center bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)] dark:bg-black"></div>
//       <p className="relative z-20 bg-gradient-to-b from-neutral-200 to-neutral-500 bg-clip-text py-8 text-4xl font-bold text-transparent sm:text-7xl">
//         {children}
//       </p>
//     </div>
      
//     </div>
//     </NextThemesProvider>
//     </body>
//     </html>
//   );
// }
// export const Logo = () => {
//   return (
//     <Link
//       href="#"
//       className="relative z-20 flex items-center space-x-2 py-1 text-sm font-normal text-black"
//     >
      
//       <div className="h-5 w-6 shrink-0 rounded-tl-lg rounded-tr-sm rounded-br-lg rounded-bl-sm" >🔒</div>
//       <motion.span
//         initial={{ opacity: 0 }}
//         animate={{ opacity: 1 }}
//         className="font-large whitespace-pre text-black dark:text-white"
//       >
//         GenPass
//       </motion.span>
//     </Link>
//   );
// };
// export const LogoIcon = () => {
//   return (
//     <Link
//       href="#"
//       className="relative z-20 flex items-center space-x-2 py-1 text-sm font-normal text-black"
//     >
//       🔒
//       {/* <div className="h-5 w-6 shrink-0 rounded-tl-lg rounded-tr-sm rounded-br-lg rounded-bl-sm bg-black dark:bg-white" /> */}
//     </Link>
//   );
// };

// // Dummy dashboard component with content
// const Dashboard = () => {
//   return (
//    <>
//    </>
//   );
// };


